// First-party funnel event types (stored in Event.type).

const FUNNEL_EVENT_TYPES = Object.freeze({
  READERS_AGREE_PAGE_VIEW: 'READERS_AGREE_PAGE_VIEW',
  READERS_AGREE_TIME_ON_PAGE: 'READERS_AGREE_TIME_ON_PAGE',
  READERS_AGREE_SCROLL_DEPTH: 'READERS_AGREE_SCROLL_DEPTH',
  READERS_AGREE_AMAZON_CLICK: 'READERS_AGREE_AMAZON_CLICK',
  READERS_AGREE_BN_CLICK: 'READERS_AGREE_BN_CLICK',
  READERS_AGREE_SAMPLE_CHAPTERS_CLICK: 'READERS_AGREE_SAMPLE_CHAPTERS_CLICK',

  SAMPLE_CHAPTERS_PAGE_VIEW: 'SAMPLE_CHAPTERS_PAGE_VIEW',
  SAMPLE_CHAPTER_OPEN: 'SAMPLE_CHAPTER_OPEN',
  SAMPLE_CHAPTER_TIME_ON_PAGE: 'SAMPLE_CHAPTER_TIME_ON_PAGE',
  SAMPLE_CHAPTERS_BUY_CLICK: 'SAMPLE_CHAPTERS_BUY_CLICK',
  SAMPLE_CHAPTERS_HUB_CLICK: 'SAMPLE_CHAPTERS_HUB_CLICK',

  CHECKOUT_STARTED: 'CHECKOUT_STARTED',
  PURCHASE_COMPLETED: 'PURCHASE_COMPLETED',
});

const FUNNEL_EVENT_TYPE_SET = new Set(Object.values(FUNNEL_EVENT_TYPES));

const SAMPLE_CHAPTER_IDS = new Set(['1', '2', '9', '45']);

function isFunnelEventType(type) {
  return FUNNEL_EVENT_TYPE_SET.has(type);
}

function isSampleChapterId(id) {
  return SAMPLE_CHAPTER_IDS.has(String(id));
}

module.exports = {
  FUNNEL_EVENT_TYPES,
  FUNNEL_EVENT_TYPE_SET,
  SAMPLE_CHAPTER_IDS,
  isFunnelEventType,
  isSampleChapterId,
};
