// First-party funnel event types (stored in Event.type).

const FUNNEL_EVENT_TYPES = Object.freeze({
  READERS_AGREE_PAGE_VIEW: 'READERS_AGREE_PAGE_VIEW',
  READERS_AGREE_TIME_ON_PAGE: 'READERS_AGREE_TIME_ON_PAGE',
  READERS_AGREE_SCROLL_DEPTH: 'READERS_AGREE_SCROLL_DEPTH',
  READERS_AGREE_AMAZON_CLICK: 'READERS_AGREE_AMAZON_CLICK',
  READERS_AGREE_BN_CLICK: 'READERS_AGREE_BN_CLICK',
  READERS_AGREE_BUY_CLICK: 'READERS_AGREE_BUY_CLICK',
  READERS_AGREE_BUY_DIRECT_CLICK: 'READERS_AGREE_BUY_DIRECT_CLICK',
  READERS_AGREE_EMAIL_SUBMITTED: 'READERS_AGREE_EMAIL_SUBMITTED',
  READERS_AGREE_BRIDGE_VIEW: 'READERS_AGREE_BRIDGE_VIEW',
  READERS_AGREE_BRIDGE_BUY_DIRECT_CLICK: 'READERS_AGREE_BRIDGE_BUY_DIRECT_CLICK',
  READERS_AGREE_BRIDGE_ALT_RETAILER_CLICK: 'READERS_AGREE_BRIDGE_ALT_RETAILER_CLICK',
  READERS_AGREE_BRIDGE_BACK_TO_RETAILER_CLICK: 'READERS_AGREE_BRIDGE_BACK_TO_RETAILER_CLICK',
  READERS_AGREE_BRIDGE_EMAIL_SUBMITTED: 'READERS_AGREE_BRIDGE_EMAIL_SUBMITTED',
  PROSPECT_NURTURE_SENT: 'PROSPECT_NURTURE_SENT',
  READERS_AGREE_SAMPLE_CHAPTERS_CLICK: 'READERS_AGREE_SAMPLE_CHAPTERS_CLICK',
  READERS_AGREE_START_READING_CLICK: 'READERS_AGREE_START_READING_CLICK',

  SAMPLE_CHAPTERS_PAGE_VIEW: 'SAMPLE_CHAPTERS_PAGE_VIEW',
  SAMPLE_CHAPTER_OPEN: 'SAMPLE_CHAPTER_OPEN',
  SAMPLE_CHAPTER_TIME_ON_PAGE: 'SAMPLE_CHAPTER_TIME_ON_PAGE',
  SAMPLE_CHAPTERS_BUY_CLICK: 'SAMPLE_CHAPTERS_BUY_CLICK',
  SAMPLE_CHAPTERS_HUB_CLICK: 'SAMPLE_CHAPTERS_HUB_CLICK',

  CHECKOUT_STARTED: 'CHECKOUT_STARTED',
  PURCHASE_COMPLETED: 'PURCHASE_COMPLETED',

  JODY_APPEAR: 'JODY_APPEAR',
  JODY_CHAPTER_COMPLETED: 'JODY_CHAPTER_COMPLETED',
  JODY_REMEMBER_PLACE_ACCEPT: 'JODY_REMEMBER_PLACE_ACCEPT',
  JODY_REMEMBER_PLACE_DECLINE: 'JODY_REMEMBER_PLACE_DECLINE',
  JODY_EMAIL_ENTERED: 'JODY_EMAIL_ENTERED',
  JODY_EMAIL_VERIFIED: 'JODY_EMAIL_VERIFIED',
  JODY_UPDATES_ACCEPT: 'JODY_UPDATES_ACCEPT',
  JODY_UPDATES_DECLINE: 'JODY_UPDATES_DECLINE',
  RETURNED_WITH_JODY: 'RETURNED_WITH_JODY',
});

const FUNNEL_EVENT_TYPE_SET = new Set(Object.values(FUNNEL_EVENT_TYPES));

const SAMPLE_CHAPTER_IDS = new Set(['1', '2', '9', '45']);

function isFunnelEventType(type) {
  return FUNNEL_EVENT_TYPE_SET.has(type);
}

function isSampleChapterId(id) {
  return SAMPLE_CHAPTER_IDS.has(String(id));
}

module.exports = {
  FUNNEL_EVENT_TYPES,
  FUNNEL_EVENT_TYPE_SET,
  SAMPLE_CHAPTER_IDS,
  isFunnelEventType,
  isSampleChapterId,
};
